set_project("brushed")
set_policy("build.warning",true)
set_policy("package.install_locally", true)
add_rules("mode.debug","mode.release","mode.releasedbg","mode.minsizerel","plugin.compile_commands.autoupdate")

package("fwog")
    add_deps("cmake")
    add_versions("1.0.0","ca0317d3cf0f8b15656ed7e6508df4e2e4ac27fe")
    add_urls("https://github.com/JuanDiegoMontoya/Fwog.git")
    on_install(function (package)
        import("package.tools.cmake").install(package)
    end)
package_end()
add_requires("glm","cmake","imgui v1.91.8-docking","glfw","glad","fwog",{configs = {glfw = true, opengl3 = true, extensions = "GL_ARB_bindless_texture"}})

target("brushed")
	set_kind("binary")
	set_languages("c++26")
	add_includedirs("brushed/include",{public = true})
	add_includedirs("brushed/src",{public = false})
	add_packages("glm","imgui","glfw","glad","fwog")
	add_defines("FWOG_DEBUG","GLM_FORCE_SWIZZLE","GLM_FORCE_XYZW_ONLY","GLM_ENABLE_EXPERIMENTAL")
	add_files("brushed/src/brushed/*.cpp")
target_end()