set_project("brushed")
set_policy("build.warning",true)
set_policy("package.install_locally", true)
add_rules("mode.debug","mode.release","mode.releasedbg","mode.minsizerel","plugin.compile_commands.autoupdate", {outputdir = "$(buildir)"})

add_requires("glm","imgui","glfw","glad")
target("brushed")
	set_kind("binary")
	set_languages("c++23")
	add_includedirs("brushed/include",{public = true})
	add_packages("glm","imgui","glfw","gl","glad")
	add_defines("GLM_FORCE_SWIZZLE","GLM_FORCE_XYZW_ONLY")
	add_files("brushed/src/brushed/*.cpp")
target_end()